title: Threat Actor Detection Lab
logo: <iframe width="560" height="315" src="https://www.youtube.com/embed/RWE0wywoazo?si=CsxMfD73GjA_1Kbg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
theme: jekyll-theme-minimal
